/* eslint-disable */
// AUTO-GENERATED by scripts/sync-gallery-assets.mjs — do not edit by hand.
// Re-run: node scripts/sync-gallery-assets.mjs

export type InspirationGalleryExtraSlide = {
  key: string;
  src: string;
  category: 'wedding' | 'corporate' | 'private' | 'facilities';
};

export const inspirationGalleryExtraSlides: InspirationGalleryExtraSlide[] = [
  { key: 'inspirasjon-48', src: '/gallery/inspirasjon-48.png', category: 'wedding' }, // __N855326_Drammen_lier_fotografering_bryllupsfotograf-5036c1c4-dcf9-4b27-a1f7-19572e3fd5f9.png
  { key: 'inspirasjon-49', src: '/gallery/inspirasjon-49.png', category: 'wedding' }, // __N855330_Drammen_lier_fotografering_bryllupsfotograf-4e23f85e-626d-4629-8223-d2bf2159b2d3.png
  { key: 'inspirasjon-51', src: '/gallery/inspirasjon-51.png', category: 'wedding' }, // _DSCF1246_Drammen_lier_fotografering_bryllupsfotograf-50023183-41cc-46f1-9504-ef4af89c03a8.png
  { key: 'inspirasjon-53', src: '/gallery/inspirasjon-53.png', category: 'wedding' }, // _DSCF1292_Drammen_lier_fotografering_bryllupsfotograf1-01feec1e-06a2-4a6e-b44b-dfd700acedba.png
  { key: 'inspirasjon-56', src: '/gallery/inspirasjon-56.png', category: 'wedding' }, // _DSCF1309_Drammen_lier_fotografering_bryllupsfotograf1-5c42c7f5-b0ee-4ed1-b318-ed4d45945f89.png
  { key: 'inspirasjon-60', src: '/gallery/inspirasjon-60.png', category: 'wedding' }, // 122898400_389717899074104_8499580724299318997_n-52f48942-1a1f-4913-8f67-1ee2c8b5b9ea.png
  { key: 'inspirasjon-62', src: '/gallery/inspirasjon-62.png', category: 'wedding' }, // 123955039_402074097838484_5820509645511667279_n-b6982a47-0249-4b4b-81be-2487597e8ec6.png
  { key: 'inspirasjon-63', src: '/gallery/inspirasjon-63.png', category: 'wedding' }, // 124763272_402074017838492_5032804299840479610_n-eef09a5b-9260-4062-8dac-6719b4bea29b.png
  { key: 'inspirasjon-65', src: '/gallery/inspirasjon-65.png', category: 'wedding' }, // 124971143_402983291080898_43553304584249275_n-98bb8f7a-bf15-4fc4-bcc8-f6a45dca7a23.png
  { key: 'inspirasjon-66', src: '/gallery/inspirasjon-66.png', category: 'wedding' }, // 125033577_402983234414237_9216218742794933471_n-a4abfad3-1190-4c4b-bf1f-1e2eba988caa.png
  { key: 'inspirasjon-68', src: '/gallery/inspirasjon-68.png', category: 'wedding' }, // 125183551_402983067747587_8005590713137565178_n-adbab9e9-fdaf-4311-97cb-69e0d3db5189.png
  { key: 'inspirasjon-72', src: '/gallery/inspirasjon-72.png', category: 'wedding' }, // 180478553_510286967017196_2660724699262069454_n-4302ba88-7882-43e0-88c2-69666c95f2bf.png
  { key: 'inspirasjon-73', src: '/gallery/inspirasjon-73.png', category: 'wedding' }, // 2-da949b40-9e75-4295-ba85-8bfcbf2c2e0b.png
  { key: 'inspirasjon-82', src: '/gallery/inspirasjon-82.png', category: 'wedding' }, // 241464266_592913102087915_8556216086109985848_n-0a76aa75-f589-43c5-aa87-f07898bf1946.png
  { key: 'inspirasjon-107', src: '/gallery/inspirasjon-107.png', category: 'wedding' }, // 468752200_1326561468723071_2651641691333451860_n-9e1e3622-b76c-422d-9684-06b67302c5b6.png
  { key: 'inspirasjon-108', src: '/gallery/inspirasjon-108.png', category: 'wedding' }, // 470187232_1334950477884170_1574430429956827671_n-1023af36-a576-426c-81d5-4e7042915ff2.png
  { key: 'inspirasjon-109', src: '/gallery/inspirasjon-109.png', category: 'wedding' }, // 470191411_1334938444552040_1990592040269819386_n-3fe3cf76-b2b0-44fe-9848-0283465245cd.png
  { key: 'inspirasjon-111', src: '/gallery/inspirasjon-111.png', category: 'wedding' }, // 470232627_1334938161218735_1963125604391382128_n-e244f6ed-dc4a-4337-bf62-60dfa5963bcc.png
  { key: 'inspirasjon-113', src: '/gallery/inspirasjon-113.png', category: 'wedding' }, // 470723968_1339484490764102_1664011255169997729_n-74d91820-68af-486c-840d-5eec5fc0e9b6.png
  { key: 'inspirasjon-114', src: '/gallery/inspirasjon-114.png', category: 'wedding' }, // 470871719_1340264450686106_5687357889666154707_n-e32c957d-8afb-4b40-9910-37347d9c0727.png
  { key: 'inspirasjon-115', src: '/gallery/inspirasjon-115.png', category: 'wedding' }, // 470876633_1340265430686008_300663239583926768_n-58f51932-c52d-448c-816c-61d2917b2335.png
  { key: 'inspirasjon-119', src: '/gallery/inspirasjon-119.png', category: 'wedding' }, // 471194349_18480927070060866_7570505825853593368_n-adc9d1cb-91f9-4315-8f20-71749095ff7b.png
  { key: 'inspirasjon-120', src: '/gallery/inspirasjon-120.png', category: 'wedding' }, // 473188148_1353716696007548_6143376265790451072_n-7d2453ca-f81f-4153-b0a6-0a51e8ae03dd.png
  { key: 'inspirasjon-121', src: '/gallery/inspirasjon-121.png', category: 'wedding' }, // 473191296_1355892392456645_2116736943343447535_n-8e444fe7-080d-4842-a745-980ac3084e6e.png
  { key: 'inspirasjon-122', src: '/gallery/inspirasjon-122.png', category: 'wedding' }, // 473323072_1355892252456659_2748641669319294729_n-2b815995-4aad-43b4-9a70-7c6df094dbdb.png
  { key: 'inspirasjon-124', src: '/gallery/inspirasjon-124.png', category: 'wedding' }, // 473553205_1355891999123351_9091933293073228266_n-97a6646c-1e03-40e1-95d1-8fd1af3a06d2.png
  { key: 'inspirasjon-125', src: '/gallery/inspirasjon-125.png', category: 'wedding' }, // 473582504_1355892295789988_3073514870773246244_n-fdd9d1c6-2b5e-402f-82e4-f17b5dac6ad2.png
  { key: 'inspirasjon-126', src: '/gallery/inspirasjon-126.png', category: 'wedding' }, // 473582537_1355892212456663_3673740049295204865_n-2ed7d2a9-7fe6-4088-a748-346b40c227c7.png
  { key: 'inspirasjon-128', src: '/gallery/inspirasjon-128.png', category: 'wedding' }, // 473643148_1355892045790013_246058716173367902_n-b7acbf6a-fb7d-45ba-ab85-c9ff37858969.png
  { key: 'inspirasjon-129', src: '/gallery/inspirasjon-129.png', category: 'wedding' }, // 473651132_1355892275789990_5413735998366007780_n-df09322d-9308-410b-8fe9-fee0825378b3.png
  { key: 'inspirasjon-130', src: '/gallery/inspirasjon-130.png', category: 'wedding' }, // 475462937_1160284889431745_4307138492438241255_n-43e0b1a8-b937-46f0-ad03-168100986803.png
  { key: 'inspirasjon-131', src: '/gallery/inspirasjon-131.png', category: 'wedding' }, // 475993586_1160284769431757_3859191165553136702_n-857cbc99-29b4-46ee-9e0a-460bae1ba0a6.png
  { key: 'inspirasjon-134', src: '/gallery/inspirasjon-134.png', category: 'wedding' }, // 476121304_1160284759431758_7889260629837865618_n__1_-d2ec1181-f655-4d2d-ae08-e3c3e395399f.png
  { key: 'inspirasjon-138', src: '/gallery/inspirasjon-138.png', category: 'wedding' }, // 476804095_1160986412694926_953877492841957620_n-8586562d-38e0-42eb-bc55-6ee0d370aee8.png
  { key: 'inspirasjon-139', src: '/gallery/inspirasjon-139.png', category: 'wedding' }, // 476832035_1161581235968777_6754528674280006360_n-919fb620-cca0-45b9-a697-885da9486737.png
  { key: 'inspirasjon-140', src: '/gallery/inspirasjon-140.png', category: 'wedding' }, // 477803631_1167801292013438_5028879310500559083_n-83ba5de4-b2e5-4989-a0b2-37fdaef0160a.png
  { key: 'inspirasjon-141', src: '/gallery/inspirasjon-141.png', category: 'wedding' }, // 480538859_1167801728680061_5163813937802317927_n-1217e742-9edb-4383-a691-2203d6bfb075.png
  { key: 'inspirasjon-143', src: '/gallery/inspirasjon-143.png', category: 'wedding' }, // 480631115_1173949504731950_7206440589519207182_n-42da0358-579a-4a83-8790-b1f3a59b833d.png
  { key: 'inspirasjon-144', src: '/gallery/inspirasjon-144.png', category: 'wedding' }, // 480708245_1173942134732687_2097158906874032185_n-76ca6a4a-6c40-46cb-84b6-44e48b7e4b14.png
  { key: 'inspirasjon-145', src: '/gallery/inspirasjon-145.png', category: 'wedding' }, // 480968692_1173225488137685_6022005434932860215_n-57c7fad5-4db3-406f-a2db-e663abac4e47.png
  { key: 'inspirasjon-148', src: '/gallery/inspirasjon-148.png', category: 'wedding' }, // 481348989_1179238057536428_1662563578222076540_n-1b237422-deda-4c0c-845f-0083e8f54bb3.png
  { key: 'inspirasjon-149', src: '/gallery/inspirasjon-149.png', category: 'wedding' }, // 481449686_1179241184202782_2331229709842482525_n-c7011aff-3090-4a15-a02f-abd347b281cd.png
  { key: 'inspirasjon-150', src: '/gallery/inspirasjon-150.png', category: 'wedding' }, // 484031124_1190284376431796_2046750860727456566_n-6c5e2e45-311b-42ee-912a-c3d368e19550.png
  { key: 'inspirasjon-152', src: '/gallery/inspirasjon-152.png', category: 'wedding' }, // 484306996_1188283346631899_5504804345129766973_n-8a185118-46c0-4898-a26e-5d40bc6c232a.png
  { key: 'inspirasjon-154', src: '/gallery/inspirasjon-154.png', category: 'wedding' }, // 485745655_1197330829060484_8738899996256663393_n-8081e02f-b41c-4678-960c-f3351d0c5cd0.png
  { key: 'inspirasjon-155', src: '/gallery/inspirasjon-155.png', category: 'wedding' }, // 485849618_1197330585727175_4608906197906304068_n-670d95a1-04f6-414b-aa9c-7b39ecc09909.png
  { key: 'inspirasjon-157', src: '/gallery/inspirasjon-157.png', category: 'wedding' }, // 485868864_1197330589060508_5902149943546090836_n-baefd333-e3aa-47c6-8cac-59e9bad2f6d9.png
  { key: 'inspirasjon-158', src: '/gallery/inspirasjon-158.png', category: 'wedding' }, // 486000730_1197330552393845_8558538757157227869_n-81e5ef1a-a1de-40e4-b9f3-445bd5df4903.png
  { key: 'inspirasjon-160', src: '/gallery/inspirasjon-160.png', category: 'wedding' }, // 487698923_1231043195695420_2510561597320243896_n-0a23980b-9e7d-4ed1-9b02-4b5149517a6b.png
  { key: 'inspirasjon-161', src: '/gallery/inspirasjon-161.png', category: 'wedding' }, // 487774017_1207928398000727_8575613689543372645_n-d1f1101f-8538-4e0a-a5cb-6b861f8267f1.png
  { key: 'inspirasjon-162', src: '/gallery/inspirasjon-162.png', category: 'wedding' }, // 487812626_1204100395050194_6729314883999306629_n-ccc8c7b7-2df6-40ab-a3d6-7f3c87b761cc.png
  { key: 'inspirasjon-163', src: '/gallery/inspirasjon-163.png', category: 'wedding' }, // 487971993_1232518452214561_3537245602222992365_n-46db8cdc-bb43-4b80-9608-0171c0db42aa.png
  { key: 'inspirasjon-165', src: '/gallery/inspirasjon-165.png', category: 'wedding' }, // 488044718_1232518798881193_5664763128320667260_n-599b8f4b-411b-4b11-bd6f-b2dbfeb0c56f.png
  { key: 'inspirasjon-167', src: '/gallery/inspirasjon-167.png', category: 'wedding' }, // 490382610_1243637534435393_9106670154673679538_n-b41db26c-c0ed-4b4c-8e5a-91fd4c4232e0.png
  { key: 'inspirasjon-169', src: '/gallery/inspirasjon-169.png', category: 'wedding' }, // 490467756_1243637207768759_819221950154872867_n-23e9d481-78cb-4f8b-a17d-8c189f53cc0f.png
  { key: 'inspirasjon-172', src: '/gallery/inspirasjon-172.png', category: 'wedding' }, // 503623334_1262547762538790_8964792636061054096_n-f07427f9-6db0-49eb-a3b5-739f0e589101.png
  { key: 'inspirasjon-174', src: '/gallery/inspirasjon-174.png', category: 'wedding' }, // 504705549_1266621512131415_3316916307162109045_n-ebd84fa0-511b-42da-8123-aacc04b827eb.png
  { key: 'inspirasjon-175', src: '/gallery/inspirasjon-175.png', category: 'wedding' }, // 504947622_1266621368798096_778325639992523412_n-d426b286-e1c8-4010-85c3-1c2ef59806fc.png
  { key: 'inspirasjon-177', src: '/gallery/inspirasjon-177.png', category: 'wedding' }, // 505288593_1266621682131398_3221353277174805191_n-4da61272-bd3b-472d-9400-d546f5702f5a.png
  { key: 'inspirasjon-178', src: '/gallery/inspirasjon-178.png', category: 'wedding' }, // 505410390_1266621778798055_2195692700491283204_n-d707ce92-288c-4a55-96b5-62a4659f6d42.png
  { key: 'inspirasjon-179', src: '/gallery/inspirasjon-179.png', category: 'wedding' }, // 509361752_1277756071017959_4871698513545194257_n-dc50856d-650a-4b4f-82db-e4a04875eacd.png
  { key: 'inspirasjon-180', src: '/gallery/inspirasjon-180.png', category: 'wedding' }, // 509415705_1277755954351304_6737020321976226634_n-ac98facc-80b9-487d-9301-f73207f4a63e.png
  { key: 'inspirasjon-183', src: '/gallery/inspirasjon-183.png', category: 'wedding' }, // 515555313_1290902759703290_743986379646951307_n-509a6559-70f3-4728-842c-2a8493d07f13.png
  { key: 'inspirasjon-185', src: '/gallery/inspirasjon-185.png', category: 'wedding' }, // 528292538_1316573757136190_4866440439777684407_n-f4a6720b-dadc-4235-884e-e131342641b9.png
  { key: 'inspirasjon-190', src: '/gallery/inspirasjon-190.png', category: 'wedding' }, // 544555426_1346594767467422_2574032772675353295_n-02c42d48-f881-4a22-bd4f-e90e6f4ee118.png
  { key: 'inspirasjon-192', src: '/gallery/inspirasjon-192.png', category: 'wedding' }, // 544925103_1346594607467438_6565403714224831763_n-46f69a63-7893-4840-b288-26a9f29f2466.png
  { key: 'inspirasjon-193', src: '/gallery/inspirasjon-193.png', category: 'wedding' }, // 545347092_1346594657467433_5633100872561727374_n-935cbc86-b436-4426-962e-7aa83bb86a93.png
  { key: 'inspirasjon-195', src: '/gallery/inspirasjon-195.png', category: 'wedding' }, // 691_04456ad6-78a5-4800-81d8-d9cf7b9fbc85-6de06181-6fe0-488f-8b1f-d244815e3c55.png
  { key: 'inspirasjon-196', src: '/gallery/inspirasjon-196.png', category: 'wedding' }, // 691_15eeeea2-46de-453e-8ab2-e053c650d789-d80e57c3-6241-41dd-bff3-25c0f33fe41a.png
  { key: 'inspirasjon-199', src: '/gallery/inspirasjon-199.png', category: 'wedding' }, // 71169880_125668518812378_1550295950461763584_n-1688d795-c754-4a5b-99c3-41037155f3d0.png
  { key: 'inspirasjon-201', src: '/gallery/inspirasjon-201.png', category: 'wedding' }, // 71486954_125668162145747_4433751231365644288_n-b65f10d6-35e5-4d52-9147-7ae1e3f571bb.png
  { key: 'inspirasjon-205', src: '/gallery/inspirasjon-205.png', category: 'wedding' }, // Bryllupp-aa4d77d7-f070-438f-a971-931cae1c8328.png
  { key: 'inspirasjon-207', src: '/gallery/inspirasjon-207.png', category: 'wedding' }, // dekor-ddc0a193-9d57-4c37-b2b8-ce5a7ed116b2.png
  { key: 'inspirasjon-208', src: '/gallery/inspirasjon-208.png', category: 'facilities' }, // DJI_0442-scaled-4ff2b1af-6d87-4005-ac35-5b72d874b9e8.png
  { key: 'inspirasjon-233', src: '/gallery/inspirasjon-233.png', category: 'facilities' }, // felles-3c67a37d-6df7-4935-9e92-c9a1e721741a.png
  { key: 'inspirasjon-234', src: '/gallery/inspirasjon-234.png', category: 'wedding' }, // folk-8e689fa5-9aa6-49a0-b206-68d22e9daea6.png
  { key: 'inspirasjon-235', src: '/gallery/inspirasjon-235.png', category: 'facilities' }, // forside-0f6bbc92-28a5-46ae-b8c4-1cb771dfb62d.png
  { key: 'inspirasjon-245', src: '/gallery/inspirasjon-245.png', category: 'wedding' }, // hero-home-venue-real.png
  { key: 'inspirasjon-247', src: '/gallery/inspirasjon-247.png', category: 'wedding' }, // image-0234ec5d-3dc5-44a1-a242-a5ae9cca9ac1.png
  { key: 'inspirasjon-248', src: '/gallery/inspirasjon-248.png', category: 'wedding' }, // image-16ce7315-d76d-41a1-9784-3d56f1814bdb.png
  { key: 'inspirasjon-249', src: '/gallery/inspirasjon-249.png', category: 'wedding' }, // image-44475508-74fc-44de-95e8-54f03863b422.png
  { key: 'inspirasjon-250', src: '/gallery/inspirasjon-250.png', category: 'wedding' }, // image-52fa2d0e-cfe2-435e-9895-4451476f5f8a.png
  { key: 'inspirasjon-251', src: '/gallery/inspirasjon-251.png', category: 'wedding' }, // image-632b33e8-c7c3-4f6a-8c04-52f6e5e9fb35.png
  { key: 'inspirasjon-252', src: '/gallery/inspirasjon-252.png', category: 'wedding' }, // image-91de8c64-a1e7-4448-9ee4-b1c12efed308.png
  { key: 'inspirasjon-253', src: '/gallery/inspirasjon-253.png', category: 'wedding' }, // image-968d06ce-8589-4b8e-a3e6-e534e45e29e1.png
  { key: 'inspirasjon-254', src: '/gallery/inspirasjon-254.png', category: 'wedding' }, // image-98dac480-f198-4de4-a98f-8be49c6c5d03.png
  { key: 'inspirasjon-257', src: '/gallery/inspirasjon-257.png', category: 'wedding' }, // image-fc31df0e-00c0-4d57-b0fd-a0bdf8f6325d.png
  { key: 'inspirasjon-273', src: '/gallery/inspirasjon-273.png', category: 'facilities' }, // inngang-67b2fa79-43fd-46ae-9221-31cebd2d2ded.png
  { key: 'inspirasjon-274', src: '/gallery/inspirasjon-274.png', category: 'facilities' }, // inngang1-fe733ca6-b5ed-4b52-96c4-b7d0e15b3358.png
  { key: 'inspirasjon-275', src: '/gallery/inspirasjon-275.png', category: 'facilities' }, // inngang2-31b35cb9-2439-4f92-b85f-423eaf2b2cde.png
  { key: 'inspirasjon-280', src: '/gallery/inspirasjon-280.png', category: 'facilities' }, // natur-eeed62c3-3142-46fe-8b93-1a423895da81.png
  { key: 'inspirasjon-281', src: '/gallery/inspirasjon-281.png', category: 'wedding' }, // PHOTO-2026-03-27-11-57-11-7bbed695-e65e-4573-8a60-21472a172b5a.png
  { key: 'inspirasjon-282', src: '/gallery/inspirasjon-282.png', category: 'wedding' }, // Screenshot_2026-03-27_at_16.45.08-33e3225e-731b-460e-a6d0-558223555b1e.png
  { key: 'inspirasjon-283', src: '/gallery/inspirasjon-283.png', category: 'wedding' }, // Screenshot_2026-03-27_at_19.31.44-62d90c33-2353-4871-bddd-3fb443d1cc77.png
  { key: 'inspirasjon-290', src: '/gallery/inspirasjon-290.png', category: 'wedding' }, // Screenshot_2026-04-02_at_12.17.02-74164144-65b7-4745-adaa-f2e4bde71a29.png
  { key: 'inspirasjon-291', src: '/gallery/inspirasjon-291.png', category: 'wedding' }, // Screenshot_2026-04-06_at_12.10.53-a47801bd-fe79-42c7-b438-653b5b67de95.png
  { key: 'inspirasjon-293', src: '/gallery/inspirasjon-293.png', category: 'wedding' }, // Screenshot_2026-04-06_at_13.11.00-a0e54082-2de7-41c4-b3dc-e1ee525f7073.png
  { key: 'inspirasjon-295', src: '/gallery/inspirasjon-295.png', category: 'wedding' }, // Screenshot_2026-04-07_at_17.53.27-84a7f2e5-12fe-419b-a404-5faf3dd921bb.png
  { key: 'inspirasjon-296', src: '/gallery/inspirasjon-296.png', category: 'wedding' }, // Screenshot_2026-04-07_at_18.27.45-d6f56eae-abed-46d6-971b-b3bd96bf0e7b.png
  { key: 'inspirasjon-299', src: '/gallery/inspirasjon-299.png', category: 'wedding' }, // tempImagebD8hJl-scaled-3665319b-d6c1-4cf1-aa76-28b58fe928b7.png
  { key: 'inspirasjon-300', src: '/gallery/inspirasjon-300.png', category: 'wedding' }, // we2-7a9292d0-df97-42bb-8034-f02e75c1a064.png
];
